export const START = '/start'
export const TODO_DASHBOARD = '/todo-dashboard'
export const TODO = '/todo'
export const EDIT = '/edit'
export const TODO_TEST = '/todo-test'
export const CURRENT_DAY = '/current-day'
